package org.firstinspires.ftc.teamcode.telephony;

public enum State {
    ADJUSTING_ORIENTATION,
    UPDATING_FIELD_GRAPH,
    GETTING_IF_PARK,
    SCANNING_AVAILABLE_ELEMENTS,
    CALCULATING_PARKING_TRAJECTORY,
    CALCULATING_DESTINATION_TRAJECTORY,
    PARKING,
    MOVING_TO_DESTINATION,
    CAPPING
}
